### ISSUE TITLE
Abgabe von Dateien

### ISSUE THREAD

**Issue by Kirdock** [Kirdock/Moodle2.0#10]
POST /user/kreuzel/attachement

Anhang für ein Beispiel hinzufügen oder aktualisieren (finishedExample)

Request:
- file
- id (exampleId)

Response: egal

**Comment by Kirdock** [comment]
Zusätzlich: GET /user/kreuzel/attachement/{exampleId}

**Comment by peterthepipp** [comment]
Änderung finishesExample table
attachment von CLOB zu BLOB
spalte file_Name hinzugefügt
