### ISSUE TITLE
Anwesenheitsliste generieren

### ISSUE THREAD

**Issue by Kirdock** [Kirdock/Moodle2.0#28]
GET /course/{id}/attendanceList

Inhalt:
- Matrikelnrnummer
- Vorname
- Nachname
- ein leeres Feld zum Unterschreiben

**Comment by peterthepipp** [comment]
bis auf die sprache funktioniert des schon

**Comment by Kirdock** [comment]
- Spaltenreihenfolge sollte sein:
  Matrikelnummer, Nachname, Vorname, Unterschrift
- Sortiert nach Nachname
- `MatrikelNummer` => `Matrikelnummer`
- `MatriculationNumber` => `Matriculation number`

**Comment by Kirdock** [comment]
- Es sollte wie bei der Kreuzelliste sortiert werden nach:  `surname -> forename -> matriculationNumber`.
- Die Reihenfolge der Spalten ist falsch. Sie sollte sein `matriculationNumber -> surname -> forename -> signature`
