### ISSUE TITLE
Präsentierte Beispiele den Kursbenutzern anhängen

### ISSUE THREAD

**Issue by Kirdock** [Kirdock/Moodle2.0#30]
Anpassung GET /users/course/{courseId}
Zusätzlich ein Array für jeden assignedUser (also für jeden User der im Kurs ist bzw. die Rolle "s" hat) (User join mit finishedExample Zwischentabelle where presented == true, für diesen Kurs):
data (presented examples) <Array>
- exampleName
- parentOrder
- order
- exampleId

Aufgrund des Arrays (array.length) hab ich dann die Anzahl wie oft ein Student presented hat
Die Info “exampleName” deswegen, damit ich das in der Liste der Präsentierungen gleich so ausgeben kann mit User und Beispiel.

Ich hab dann ja beim Kurs (Admin/Owner-Ansicht) eine neue Tabelle mit den Zuordnungen. Diese kann ich dann selbst aus dem Result von “GET /users/course/{courseId}” zusammenbauen.
Sortiert wird diese Tabelle nach ParentOrder, dann nach order, dann nach martikelnummer.
Die Id brauche ich dann fürs mögliche Löschen

**Comment by Kirdock** [comment]
Falsche Implementierung
`GET /course/{id}` wird nicht gemeint, sondern `GET /users/course/{courseId}`

**Comment by Kirdock** [comment]
Vorgehensweise wird komplett geändert:
Bei `GET /users/course/{courseId}` soll den zugeteilten Nutzern nur die Anzahl der präsentierten Beispiele zusätzlich angegeben werden. Die Beispielinformation wird nicht mehr benötigt

**Comment by Kirdock** [comment]
Wird `presentedCount` erst gesezt, wenn es ein präsentiertes Beispiel gibt?
`presentedCount` ist nicht im Response.
Expected: 0 oder höher.

Es gibt noch ein nicht gebrauchtes Attribut im Response `presentedExamples <Array>`

**Comment by peterthepipp** [comment]
das mit  presentedCount hob i zuerst übersehen

**Comment by Kirdock** [comment]
#31 wird zum Testen benötigt
