### ISSUE TITLE
Sonderzeichen richtig speichern

### ISSUE THREAD

**Issue by Kirdock** [Kirdock/Moodle2.0#34]
Sonderzeichen werden nicht richtig in der Datenbank gespeichert bzw. zurückgegeben

**Comment by peterthepipp** [comment]
Konst du amol probieren ob bei dir z.b. beim register users sonderzeichen jetzt richtig in die datenbank gespeichert werden?

bei mir lokal tritt der fehler auf amol nirma auf

**Comment by Kirdock** [comment]
Noch immer falsch.
Kodierung: ANSI

UTF8 funktioniert

Wir müssten abklären, welche Kodierung genommen wird

**Comment by Kirdock** [comment]
Als Standardkodierung wird UTF-8 genommen
