### ISSUE TITLE
GET /example/{id}

### ISSUE THREAD

**Issue by Kirdock** [Kirdock/Moodle2.0#35]
POST:
expected: `supportedFileTypes`:[1,2,3]
got: `supportedFileTypes`:[{id:1}, {id:2}, {id:3}]

GET:
'supportedFileTypes`:[{id:1}, {id:2}, {id:3}

POST funktioniert nicht, wenn ich die Daten wie von GET bekomme

Such dir aus, bei welcher Schnittstelle du das anpassen willst

**Comment by peterthepipp** [comment]
bei get Example bekommts jetzt in der form zurück [1,2,3]
