### ISSUE TITLE
POST/DELETE example

### ISSUE THREAD

**Issue by Kirdock** [Kirdock/Moodle2.0#36]
"finishedExample" Zwischentabelle muss angepasst bzw. ein oder mehrere Einträge gelöscht werden, falls
- Ein Beispiel gelöscht wird
- Bei einem Beispiel ein Unterbeispiel angelegt wird (Das Haupt- bzw. Über- bzw. Parentexample kann ja nicht gekreuzelt werden)

**Comment by peterthepipp** [comment]
1) wird durch foreign key und delete cascade bereits gemacht
2) beim anlegen vom einen example wird überprüft ob ein Parentexample angegeben ist. Wenn ja werden alle einträge auf der finishesExample tabelle für dieses parent example gelöscht

**Comment by Kirdock** [comment]
Vorgehen:
1. Übungsblatt angelegt
2. Beispiel 1 (5 Punkte), 2 (10 Punkte), 3 (5 Punkte) angelegt
3. Student kreuzelt 1,2,3 und hat somit 20 von 20 Punkten
4. Bei Beispiel 2 wird ein Unterbeispiel erstellt (2 Punkte)
5. Student hat auf einmal 10 von 22 Punkten

-->Beispiel 2 wurde in der Zwischentabelle nicht gelöscht
-->Es sollten insgesamt 12 Punkte sein

Wenn bei Beispiel 2 ein Unterbeispiel erstellt wird soll

1. Die Punkteanzahl auf 0 gesetzt werden
2. Der Zwischeneintrag für alle Studenten gelöscht werden
