### ISSUE TITLE
Kurs: Kreuzelliste der Studenten

### ISSUE THREAD

**Issue by Kirdock** [Kirdock/Moodle2.0#39]
Im Admin-Panel soll es möglich sein, die Kreuzelliste zu sehen (nicht nur PDF) und gegebenfalls Kreuzel wegnehmen/hinzufügen.
Zusätzliches Attribut bei `GET /course/{id}` `kreuzel` oder `kreuzelList`
Bedingung: state != "n"
Inhalt:
- `matriculationNumber`
- `surname`
- `forename`
- `exerciseSheetName`
- `state` //wird gebraucht um zu unterscheiden ob "nicht sicher" oder "ja"
- `exampleName`
- `exampleId `//wird zum Löschen benötigt

Desweiteren sollte `POST /user/kreuzel` angepasst werden
Zusätzliches Attribut `matriculationNumber <optional>`. Falls `matriculationNumber` im Body, dann diese nehmen, sonst `token.getMatriculationNumber()` (also dann Admin/Owner, sonst Student).
Natürlich gilt, dass Admin keine Beschränkungen hat, der Owner das nur darf, wenn sich Student und Beispiel in seinem Kurs befinden.

**Comment by Kirdock** [comment]
Ok, sry wir strukturieren das komplett um.
Die Kreuzel sollen nicht in course.kreuzel mitgegeben werden.
Stattdessen brauch ich eine zusätzliche API
`GET /exerciseSheet/{exerciseSheetId}/kreuzel`
Hier bekomme ich ALLE Beispiele zu ALLEN Studenten für dieses Übungsblatt (also auch wenn `state == 'n' bzw. nicht vorhanden; wenn nicht vorhanden, dann `state = 'n'``).
Inhalt:
- `includeThird` //wird benötigt damit man bei der Kreuzelvergebung die richtigen Optionen hat
- `examples <Array>` //Alle Beispiele außer Überbeispiele; sortiert nach `order`;
  - `name`
  - `id`
- `kreuzel <Array>`
  - `matriculationNumber`
  - `surname`
  - `forename`
  - `states <string[]>` //state für jedes Beispiel; gleich sortiert wie das Attribut `examples`

Die `POST /user/kreuzel` Änderung kann somit verworfen werden.
Stattdessen wird `POST /course/kreuzelMulti` benötigt.
Response: `<Array>`
- `exampleId`
- `matriculationNumber`
- `state`

Zur Veranschaulichung:
![image](https://user-images.githubusercontent.com/11599148/84536516-4c44e980-acee-11ea-8154-0b9c811cf5f9.png)

**Comment by peterthepipp** [comment]
kreuzel <Array> sollte des nit als subarray von an example array eintrag sein ?

**Comment by Kirdock** [comment]
Wäre dann mit den `states` um einiges komplizierter. Ich brauch die Beispielnformationen nicht als Spalte, sodnern als Zeile. Wenn ich durch die examples durchiterieren würde, hätte ich, nach einer Iteration, alle Studenten und EIN Beispiel. Zweite Iteration hat die Studenteninfo redundant und dann bekomme ich das zweite Beispiel

**Comment by Kirdock** [comment]
Zusätzliche Informaiton für meine Logik:
`kreuzel` ist der Tabelleninhalt, wie du ihn im obrigen Kommentar siehst.
`name` in `examples` ist für die Überschrift der Tabelle.
`exampleId` und `exampleName` schreib ich nicht in `states` dazu, da ich diese Information sonst redundant für jeden Studenten habe.
Beim Speichern merge ich die `states` mit `examples` über den Index (weil gleich sortiert) um die `exampleId` zu bekommen.

**Comment by peterthepipp** [comment]
"Die POST /user/kreuzel Änderung kann somit verworfen werden."

welche änderung meinst da?
Das man ein Array mitgibt und nicht nur einen eintrag?

**Comment by Kirdock** [comment]
Siehe erstes Kommentar

> Desweiteren sollte POST /user/kreuzel angepasst werden
> Zusätzliches Attribut matriculationNumber <optional>. Falls matriculationNumber im Body, dann diese nehmen, sonst token.getMatriculationNumber() (also dann Admin/Owner, sonst Student).
> Natürlich gilt, dass Admin keine Beschränkungen hat, der Owner das nur darf, wenn sich Student und Beispiel in seinem Kurs befinden.

**Comment by peterthepipp** [comment]
Aso

**Comment by Kirdock** [comment]
`matriculationName`... muss ich noch mehr dazu sagen?

**Comment by peterthepipp** [comment]
😂 😂 
so passiert halt den besten profis a amol ^^

**Comment by Kirdock** [comment]
`GET /exerciseSheet/{exerciseSheetId}/kreuzel`
`response.kreuzel` hat eine inkonsistente/keine Sortierung. Es sollte nach Nachname, dann nach Vorname sortiert werden.

**Comment by Kirdock** [comment]
Sollte zusätzlich noch nach `matriculationNumber` sortiert werden.
Also `surname -> forename -> matriculationNumber`.
Weil es könnte theoretisch sein, dass es zwei Studenten mit gleichem Vor- und Nachnamen gibt
