### ISSUE TITLE
Sortierung der Präsentationen

### ISSUE THREAD

**Issue by Kirdock** [Kirdock/Moodle2.0#40]
`GET /course/{id}`
Es soll zuerst nach Abgabedatum, dann nach order und dann nach (sub)order sortiert werden.
Zusätzliches Attribut `exerciseSheetid` //wird für Filterung am Frontend benötigt

**Comment by peterthepipp** [comment]
"nach order und dann nach (sub)order sortiert" bedeutet z.b. examples mit order (0,1,2,3) und example 2 
hat 3 unterbeispiele (0,1,2) 
dann hab ich folgende sortierung 0,1,2,  0,1,2,  3 oder?

**Comment by Kirdock** [comment]
Genau
