### ISSUE TITLE
Beschreibung für Kurs hinzufügen

### ISSUE THREAD

**Issue by Kirdock** [Kirdock/Moodle2.0#47]
`GET /course/{id}`, `POST /course`, `GET /courseAssigned/{id}`
zusätzliches Attribut `description <html/string>`

**Comment by peterthepipp** [comment]
i hob jo bei course amol de spalten description_template hinzugefügt, is mit description des gemeint?

**Comment by Kirdock** [comment]
Nein, diese Vorlage ist für die Beispielbeschreibung
Der Kurs selbst benötigt aber auch eine Beschreibung
