### ISSUE TITLE
Zusätzliches Attribut bei Beispielen

### ISSUE THREAD

**Issue by Kirdock** [Kirdock/Moodle2.0#48]
`GET /exerciseSheet/{id}`, `GET /exerciseSheetAssigned/{id}`, ``POST /exerciseSheet``
`uploadCount <nullable>`

Bei der Zwischentabelle steht dann auch ein weiteres Attribut `remainingUploadCount`.
`POST /user/kreuzel/attachment` anpassen, dass `remainingUploadCount` um 1 reduziert wird

**Comment by peterthepipp** [comment]
welchen default wert hat remainingUploadCount?

was genau gibt uploadCount beim ExerciseSheet an?
Wie oft man da was aufe laden darf?

auf welchen wert setzt ich remainingUploadCount initial?

**Comment by Kirdock** [comment]
`uploadCount` gibt an, wie oft ein Benutzer bei einem Beispiel etwas hochladen kann.
0 ist unbegrenzt. 
`remainingUploadCount` ist initial der `uploadCount`

**Comment by Kirdock** [comment]
Eigentlich war dieses Attribut für `example` und nicht `exerciseSheet` gedacht, aber eigentlich... wäre Kurs nicht besser?

**Comment by peterthepipp** [comment]
i hät gsogt kurs

**Comment by peterthepipp** [comment]
soll i des uploadCount jetzt zum kurs tuan?

**Comment by Kirdock** [comment]
Bei offenen Fragen `questions` auf @Mitschi warten bzw. das nächste Mal fragen

**Comment by peterthepipp** [comment]
ok

**Comment by Mitschi** [comment]
Mention geht auch gut :)

**Comment by Mitschi** [comment]
Das Upload Limit soll fuer eine Aufgabe gelten.

**Comment by Kirdock** [comment]
Das ist klar. Die Sache ist nur die:
Man hat mehrere Beispiele. Sollte dann für jedes Beispiel einzeln das Upload Limit angegeben werden oder sollte es global im Kurs festgelegt werden, damit jedes Beispiel dasselbe hat?
Weil wie oft wird es vorkommen, dass Beispiel X ein niedrigeres bzw. höheres Upload Limit hat als Beispiel Y?

**Comment by Kirdock** [comment]
@Mitschi 
Das ist klar. Die Sache ist nur die:
Man hat mehrere Beispiele. Sollte dann für jedes Beispiel einzeln das Upload Limit angegeben werden können oder sollte man es global im Kurs festlegen, damit jedes Beispiel dasselbe hat?
Weil wie oft wird es vorkommen, dass Beispiel X ein niedrigeres bzw. höheres Upload Limit hat als Beispiel Y?

**Comment by Kirdock** [comment]
Oder Variante 2:
Man hat beides. Im Kurs ein weiterer Tab für "Presets", in dem man auch den default-Wert für das Upload-Limit angeben kann. Zusätzlich kann man es auch im Beispiel selbst anpassen

**Comment by Mitschi** [comment]
Variante 2 klingt am besten :) Die Zahl kann oft variieren.

**Comment by Kirdock** [comment]
Kurs: `Vorlagen` in `Voreinstellungen` umbenennen. Dieser Tab hat ein weiteres Attribut `uploadCount`.

`POST /course/descriptionTemplate` wird zu `POST /course/presets`
Attribute: 
- `description` (descriptionTemplate)
- `uploadCount`

Bei `PUT /course` ist der Initialwert für `uploadCount` 0 (0 = unbegrenzt), nicht NULL. Wird beim PUT nicht mitgegeben, wird am Server gesetzt.

`GET /course/{id}` zusätzliches Attribut `uploadCount`

`GET /exerciseSheet/{id}` bei den `examples` zusätzliches Attribut `uploadCount`. Außerdem soll `uploadCount` vom Kurs mitgegeben werden (damit ich den Wert setzen kann, wenn "Dateiabgabe" beim Beispiel abgehakt wird).
`POST /example/{id}` zusätzliches Attribut `uploadCount`
`GET /exerciseSheetAssigned/{id}`  zusätzliches Attribut `uploadCount` und `remainingUploadCount`. Initial ist `remainingUploadCount` der `uploadCount`. Falls `remainingUploadCount == 0` und `uploadCount != 0`, dann kann kein Beispiel mehr hochgeladen bzw. am Server ersetzt werden
