### ISSUE TITLE
Validatoren

### ISSUE THREAD

**Issue by Kirdock** [Kirdock/Moodle2.0#50]
Bei einem Beispiel kann nun zusätzlich ein Validator angegeben werden. Zurzeit Unit-Test Validator oder Code-Coverage Validator.

`POST /example/validator` //Wird erstellt oder ersetzt
- id //exampleId
- file //jar file oder etwas anderes, womit leicht zu arbeiten ist

Zusätzliches Attribut beim Kurs: `GET /exerciseSheet/{id}` bei den Beispielen:
- `validator` //Dateiname oder i-eine andere Information, damit ich weiß, dass bereits ein Validator hochgeladen wurde

`GET /example/{id}/validator`
Response: File //Hochgeladener Validator

Gedachtes Vorgehen bei einer Abgabe vom Studenten:
Abgabe => entpacken => jar Datei (Validator) dem Projekt hinzufügen und über Maven test starten

rückgabe wert bei Validatoren 
List<? extends Violation> validate(String fileDir)

**Comment by peterthepipp** [comment]
Abgabe is ja wenn ich des kreuzel attachment setze oder?

**Comment by Kirdock** [comment]
Genau

**Comment by peterthepipp** [comment]
Ok , woher waß i bei der abgab das des zip a maven projekt sein sollte?

Wenn supported file type so *.zip is und beim example der validator name gegeben ist?

**Comment by peterthepipp** [comment]
Sollt i ma aus dem validator(jar file) und den file namen noch den type vom validator irgendwo speichern ?

**Comment by Kirdock** [comment]
Momentan gehen wir davon aus, dass ein Zip-File ein Maven File ist
Type wird schätze ich egal sein. Wenn man maven-test laufen lässt.

**Comment by peterthepipp** [comment]
ok, also wenn datei type .zip => maven projekt

**Comment by Kirdock** [comment]
Sonst läuft der Validator eh nicht

**Comment by peterthepipp** [comment]
ok werd mal probieren ein maven projekt zu unzippen und maven clean install auszuführen

**Comment by Kirdock** [comment]
Bei der Auswahl der Datei (clientseitig) ist der Content- bzw. Blob-Type bei jar-Files auf leer gesetzt.
Ich muss das File bzw. den Blob kopieren um den Content-Type zu ändern, weil read-only.
Auch wenn der Content-Type auf `application/java-archive` geändert wird, wird am Server trotzdem `application/octet-stream` erkannt oder er erhält es so.

**Comment by Kirdock** [comment]
Kleinigkeit wegen deinem (Content-)Type Check:
Eine Jar-Datei hat, zumindest bei Chrome, einen leeren (Content-)Type. Wenn ich den Typ ändern möchte, muss ich eine neue Datei erstellen bzw. die alte kopieren, weil `File` read-only ist.

**Comment by Kirdock** [comment]
`example.submitFile` auf `true` setzen, wenn ein Validator hochgeladen wird

**Comment by peterthepipp** [comment]
ok ich prüf nicht mehr über den content type sondern die datei endung

**Comment by peterthepipp** [comment]
is dieser validator eigentlich a anzige java class oder könnten des a mehrere sein?

**Comment by Kirdock** [comment]
¯\\\_(ツ)_/¯

**Comment by peterthepipp** [comment]
Endlich hobs i geschafft die validator klasse im jar zu instanzieren und auszuführen^^

Folgendes jeder validator implementiert folgendes interface

public interface IValidator {

    List<Violation> validate(Example example, String fileDir);
}

wos gibt i beim ausführen vom validator bei der abgabe zurück ?

Bzw wos sollt in der Violation klasse stehn?

**Comment by peterthepipp** [comment]
[testValidator.zip](https://github.com/Kirdock/Moodle2.0/files/5080353/testValidator.zip)


Des sollte ein funktionierender Validator sein der halt nur eine Violation zurückgibt mit dem text "mamuts1243"

Du kannst dir deinen eigenen Validator schreiben , 

1) neues und leeres maven projekt lokal anlegen 
2) bei dem moodle2.0 maven projekt amol install ausführen, folls des nit schon host, (damit im lokalen maven repository olles drinnen ist)
3) dann kannst in deinem neuen maven projekt folgende dependency hinzufügen

 <dependency>
            <groupId>com.aau</groupId>
            <artifactId>validationSDK</artifactId>
            <version>0.0.1-SNAPSHOT</version>
        </dependency>

4) eine Java klasse erstellen und irgenwie benennen, die implementiert das interface IValidator
und in der methode validate gibst anfoch irgendwos zurück. 

5) in dem lokalen maven projekt das maven package ausführen , dann sollte in der target directory a jar file enstehen . 
6) des jar file zu an beispiel hochladen

**Comment by Kirdock** [comment]
Beim Hochladen wird nicht überprüft, ob es sich um einen güligen Validator handelt

**Comment by peterthepipp** [comment]
public final static Integer NO_VALID_VALIDATOR_FOUND_IN_JAR = 487;

Hab jetzt die Prüfung so gemacht, das überprüft wird ob ein Validator im Jar File vorhanden ist

**Comment by Kirdock** [comment]
Du hast den Commit anscheinend vergessen

**Comment by peterthepipp** [comment]
Ja hab ich sorry

**Comment by Kirdock** [comment]
Bei einer `ClassNotFoundException` bitte denselben Fehlercode zurückgeben

**Comment by Kirdock** [comment]
Außerdem gibt es einen Fehler.
Wenn ich einen Validator hochlade, welchen ich zuvor gerade erst einem anderen Beispiel zugewiesen habe, bekomme ich einen Fehler
`.\backend\attachments\validators\test\validatorRight.jar: Der Prozess kann nicht auf die Datei zugreifen, da sie von einem anderen Prozess verwendet wird.`
Hier wird anscheinend irgendwo ein `.close` beim Stream vergessen. Wenn ich IntelliJ neustarte, funktioniert es wieder.
