### ISSUE TITLE
Anpassung Kreuzelinformation zu Benutzer

### ISSUE THREAD

**Issue by Kirdock** [Kirdock/Moodle2.0#51]
`GET /user/{matriculationNumber}/kreuzel/{courseId}`
Neue Struktur:
Sortiert nach Abgabedatum, dann nach Übungsblattsortierung, dann nach Beispiel- und Unterbeispielsortierung
`<Array>`
- `exerciseSheetName`
- `<Array>` //Beispiele und Unterbeispiele
  -  `exampleId`
  - `exampleName`

**Comment by peterthepipp** [comment]
Übungsblattsortierung? Was ich weiß hama beim exercise_sheet ka sort_order

**Comment by Kirdock** [comment]
Mein damit die Sortierung nach Abgabedatum

**Comment by peterthepipp** [comment]
Also Sortierung wie folgt: das außerste array  nach abgabedatum vom Übungsblatt und das innere Array  dann nach beispiel - und unterbeispiel sortierung ?

**Comment by Kirdock** [comment]
Genau
Also:
Ü1 (01.01.2020)
--Bsp1 (order 0)
---Bsp1.1 (order 0)
---Bsp1.2 (order 1)
--Bsp2 (order 1)
Ü2 (05.01.2020)
...

**Comment by peterthepipp** [comment]
alles klar
