### ISSUE TITLE
Dateiabgabe (Student) nicht möglich

### ISSUE THREAD

**Issue by Kirdock** [Kirdock/Moodle2.0#56]
Der Benutzer muss zurzeit ein Kreuzel kreuzeln, speichern und erst dann kann er eine Datei hochladen.
Der Benutzer sollte aber eine Datei hochladen können, unabhängig davon, ob er das Beispiel gekreuzelt hat oder nicht

**Comment by peterthepipp** [comment]
also wenn der benutzer eine datei zu einen beispiel hochlädt und noch kein eintrag auf der finish_example tabelle ist. Soll einer erstellt werden mit state n oder?

**Comment by Kirdock** [comment]
Genau
