### ISSUE TITLE
Speichern eines Beispieles nicht möglich, wenn "supportedFileTypes" leer ist

### ISSUE THREAD

**Issue by Kirdock** [Kirdock/Moodle2.0#67]
Es sollte möglich sein, das Beispiel zu speichern, auch wenn `supportedFileTypes` leer ist. Man kann ja zum Beispiel nur `customFileTypes` angeben

**Comment by peterthepipp** [comment]
beim update gibts jo momentan die logik das bei submitFile = true de supported file types nit null sein dürfen 

Muss das jetzt nicht dementsprechend so geändert werden dass bei submitFile = true entweder supported file type oder custom file type gegeben sein muss?

**Comment by Kirdock** [comment]
Bei `submitFile = true`, muss zumindest ein Array von beiden (`supportedFileTypes`, `customFileTypes`) nicht leer sein.
Und das gilt nicht nur für die Erstellung eines Beispieles, sondern auch für die Aktualisierung.
