### ISSUE TITLE
Java-Skelett für Validator herunterladen

### ISSUE THREAD

**Issue by Kirdock** [Kirdock/Moodle2.0#68]
Es sollte möglich sein, eine Zip-Datei mit den Interfaces und Klassen für die Validatorerstellung herunterzuladen

**Comment by peterthepipp** [comment]
/validator/skeleton

so haßt momentan die api

**Comment by Kirdock** [comment]
Jetzt ist die Frage: Wir haben zwar 1:1 die gleichen Klassen, aber passt das auch wirklich so? Arbeiten kann der Benutzer damit nicht, weil Referenzen fehlen. Die Hybernate-Annotationen darin scheinen auch nicht das Wahre.... Wie sieht das mit Klassen aus, wenn Attribute und Funktionen fehlen? Sollte für den Benutzer eine andere Klasse zur Verfügung gestellt werden, welche am Server zu der richtigen gecasted/kopiert wird?

**Comment by peterthepipp** [comment]
weil dos jetzt mit maven submodulen gelöst wird , close i den issua amol
