### ISSUE TITLE
Fehlende Validierung beim CSV-Upload (create user)

### ISSUE THREAD

**Issue by Kirdock** [Kirdock/Moodle2.0#69]
Momentan kann ich folgendes problemlos per CSV anlegen:

- Matrikelnummer hat weniger als 8 Ziffern
- Matrikelnummer beinhaltet nicht nur Zahlen
- Einen Benutzer mit anderer Matrikelnummer aber gleichem Benutzernamen als jemand anders.
  - Login funktioniert dann danach auch nicht mehr "query did not return a unique result: 3; nested exception is javax.persistence.NonUniqueResultException: query did not return a unique result: 3"

**Comment by Kirdock** [comment]
Sollte nicht am besten eine Fehlermeldung kommen, wenn die Eingabedaten falsch sind?

**Comment by peterthepipp** [comment]
ok und wos sollte passieren wenn 3 von 4 einträgen passen und der letzte halt nicht ?

die ersten 3 anlegen und für die 4 eine fehlermeldung werfen ?
nur fehlermeldung werfen und nichts anlegen?

**Comment by Kirdock** [comment]
Richtige anlegen
Falsche im Response zurückgeben mit Zeilennummer

**Comment by Kirdock** [comment]
Die richtig angelegten Benutzer sollen aber auch im Response sein. => minimaler erneuter Fetch der Benutzer
