### ISSUE TITLE
PDF Exporte (Listen, Bewertungen,…)

### ISSUE THREAD

**Issue by Kirdock** [Kirdock/Moodle2.0#7]
Wahrscheinlich: Liste der Studenten und Liste inkl. Kreuzel

**Comment by Kirdock** [comment]
- [ ] Kreuzelliste
- [ ] Anwesenheitsliste

**Comment by Kirdock** [comment]
Kreuzelliste: Zeilenumbruch bei langen Namen; Querformat wenn mehr als X Beispiele

**Comment by peterthepipp** [comment]
So kreuzeliste sollte bis auf die sprache jetzt auch funktionieren

**Comment by Kirdock** [comment]
Kreuzelliste:
- Spaltenreihenfolge sollte sein:
  Matrikelnummer, Nachname, Vorname, Unterschrift
- Sortiert nach Nachname
- `MatrikelNummer` => `Matrikelnummer`
- `MatriculationNumber` => `Matriculation number`
- Sollte die Tabelle zentriert bleiben oder sollte sie linksbündig sein?

Entweder machen wir jetzt Vorname und Nachname in einem oder getrennt, aber nicht zwei verschiedene Varianten auf einmal (Kreuzel- und Anwesenheitsliste)!

**Comment by peterthepipp** [comment]
1) ich hätt die Tabelle zentriert gelassen
2) moch ma bei baden die spalten vor und nachname hätt i gsogt

**Comment by Kirdock** [comment]
Passt
Spaltenreihenfolge dann:
Matrikelnummer, Nachname, Vorname, etc.

Sortierung der Zeilen: nach Nachname, dann nach Vorname (dann nach Matrikelnummer)
