### ISSUE TITLE
Duplikate bei Kurs möglich

### ISSUE THREAD

**Issue by Kirdock** [Kirdock/Moodle2.0#74]
`POST /course`
Diese API berücksichtigt nicht, dass `name` und `number` zusammen unique sind. Per Update kann ich also mehrere Kurse mit gleicher Nummer und gleichem Namen anlegen.
Außerdem: soll es überhaupt möglich sein, zu einer Nummer, mehrere Namen anzulegen?
Also:
123.456 Kurs1
123.456 Kurs2

**Comment by peterthepipp** [comment]
also die kurs nummer is für sich allan nit unique?

**Comment by Kirdock** [comment]
Zurzeit nicht. Die Frage ist, ob sie es sein sollte, eigentlich schon oder?
Aber momentan ist Kurs + Nummer zusammen nicht einmal unique. Per POST wird diese Beschränkung umgangen

**Comment by peterthepipp** [comment]
I find kurs nummer sollte unique sein.

**Comment by peterthepipp** [comment]
homa wir nit amol gsogt dos innerhalb eines semesters der name und nummer unique sein mirsen ?

**Comment by Kirdock** [comment]
Ja, das ist aber momentan nicht der Fall :)

**Comment by peterthepipp** [comment]
wärs nit sinnvoller zu sagen, das nur de nummer innerhalb eines semesters unique sein muss ?

**Comment by Kirdock** [comment]
> Zurzeit nicht. Die Frage ist, ob sie es sein sollte, eigentlich schon oder?

**Comment by peterthepipp** [comment]
Ich moch jetzt nur de kurs nummer innerhalb eines semesters unique und de abfrage hab i donn beim erzeugen und updaten

**Comment by Kirdock** [comment]
Die Beschränkung wird wiederum umgangen, wenn ein Kurs kopiert wird, welcher im Zielsemester schon vorhanden ist.
