### ISSUE TITLE
Error code für Fehlermeldungen beim Kurs

### ISSUE THREAD

**Issue by Kirdock** [Kirdock/Moodle2.0#79]
Für folgende Fälle einen Statuscode zurückschicken:
- `POST /course`: Kursnummer kann nicht geändert werden, weil ein anderer Kurs diese bereits besitzt
- `POST /course/copy`: Kurs kann nicht in Semester X kopiert werden, weil es bereits Kurs mit dieser Nummer gibt

**Comment by peterthepipp** [comment]
CHANGED_COURSE_NUMBER_ALREADY_EXISTS =474;
COPIED_COURSE_NUMBER_ALREADY_EXISTS =475;
