### ISSUE TITLE
Löschen von Benutzern soll nicht den Kurs löschen

### ISSUE THREAD

**Issue by Kirdock** [Kirdock/Moodle2.0#81]
Wenn ein Benutzer gelöscht wird, werden auch alle Kurse, in dem der Benutzer Owner ist gelöscht; das sollte nicht passieren.
Wenn ein Benutzer gelöscht wird, soll der Owner bei allen Kursen, in dem der Benutzer Owner war, auf Admin gesetzt werden

**Comment by peterthepipp** [comment]
Bei der Course Tabelle wurde beim foreign key das delete on cascade entfernt. 

ALTER TABLE course DROP CONSTRAINT FOREIGN_KEY_OWNER;
ALTER TABLE course ADD CONSTRAINT FOREIGN_KEY_OWNER FOREIGN KEY (owner) references USER;

damit sollte die Tabelle manuell aktualisiert werden können, ohne die tabelle zu löschen und neu anzulegen
